GET http://localhost:3000/upload
Content-Type: application/json

{
    "name": "Rishabh",
    "univ": "vit-vellore"
}

###
POST http://localhost:3000/upload

{
    "file":"C:/Users/Rishabh kumar pandey/AppData/Roaming/Sublime Text 3/Packages/User/CF874/A.cpp"
}
