GET http://localhost:3000/upload
Content-Type: application/json

{
    "name": "Rishabh",
    "univ": "vit-vellore"
}

###
POST http://localhost:3000/product
Content-Type: application/json

{
    "name": "Rishabh",
    "quantity": 2024,
    "price": 200
}
